apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crossform.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crossform.fullname" . }}
rules:
  - apiGroups:
      - crossform.io
    resources:
      - xmodules
    verbs:
      - get
      - list
      - watch
